import type { MysteryTruthGraph } from './types';

/**
 * 剧情正典的唯一事实源。canonicalTruth 只能留在事实层，不能直接传给编剧。
 * revelation 文本按“氛围 → 暗示 → 线索 → 确认”逐层增加信息量。
 */
export const MYSTERY_TRUTH_GRAPH: MysteryTruthGraph = {
  version: '2026-07-19.1',
  facts: [
    {
      id: 'shared-apron-missing',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '文穗穿校服离家，却把绿色围裙叠在书包里带走；她没有准备正常上学。',
      characters: ['fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '衣柜里有一处不自然的空缺。',
        hint: '文穗常穿的绿色围裙不在衣柜里。',
        clue: '文穗穿校服出门，却同时带走了绿色围裙；她今天不只打算去学校。',
      },
      availability: { minCycle: 1, locations: ['home'] },
    },
    {
      id: 'shared-school-absence',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '文穗到过校门口但没有进校，并声称自己已经请假。',
      characters: ['fumi', 'school-guard'],
      locations: ['school'],
      revelations: {
        hint: '门卫记得文穗在校门口短暂停留。',
        clue: '文穗到过校门口，却没有进校；她对门卫说今天已经请假。',
      },
      availability: { minCycle: 1, locations: ['school'] },
    },
    {
      id: 'shared-male-leave-call',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '学校的请假电话由一名男性拨打；在路线 C 中拨打者是解离状态下的玩家。',
      characters: ['player', 'school-guard'],
      locations: ['school', 'home'],
      revelations: {
        atmosphere: '请假记录里有一个说不通的小细节。',
        hint: '请假电话不是文穗本人打的。',
        clue: '门卫确认，替文穗请假的人是男性。',
      },
      availability: { minCycle: 2, locations: ['school'] },
    },
    {
      id: 'shared-water-tower-secret',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '废弃水塔是文穗的秘密据点，她在此调查自己的孤儿院身世。',
      characters: ['fumi'],
      locations: ['water-tower'],
      revelations: {
        atmosphere: '水塔里残留着长期有人活动的痕迹。',
        hint: '刻痕、零食袋和耗尽的电池都属于同一个常客。',
        clue: '笔记与墙上刻痕表明，这里是文穗调查自己身世的秘密据点。',
        confirmation: '文穗多次来水塔整理孤儿院、院长与生父相关资料。',
      },
      availability: { minCycle: 2, locations: ['water-tower'] },
    },
    {
      id: 'shared-detective-tail',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '侦探 A 赵刚在暴雨日上午尾随文穗。',
      characters: ['fumi', 'detective-a', 'morning-witness'],
      locations: ['mountain-trail'],
      revelations: {
        atmosphere: '晨练者记得雨里两个人始终保持着相近距离。',
        hint: '一个寸头男人跟在文穗后面，距离近得不像偶然同路。',
        clue: '晨练者的证词可确认赵刚曾沿山路尾随文穗。',
      },
      availability: { minCycle: 2, locations: ['mountain-trail'] },
    },
    {
      id: 'red-herring-part-time-job',
      route: 'shared',
      kind: 'red-herring',
      canonicalTruth: '围裙与请假容易使玩家误以为文穗秘密打工，但这不是她失踪的根因。',
      characters: ['fumi'],
      locations: ['home', 'supermarket'],
      revelations: {
        hint: '她带走围裙，也许是瞒着你去做一份临时工作。',
      },
      availability: { minCycle: 1 },
    },
    {
      id: 'a-sacrifice-list',
      route: 'A',
      kind: 'evidence',
      canonicalTruth: '周德明持有“阳极之地”名单，文穗因在孤儿院生活超过三年而被列为献祭目标。',
      characters: ['fumi', 'old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '老人内室里有被刻意藏起的名单。',
        hint: '名单把孤儿院称作“至阳之地”，其中一个名字与文穗有关。',
        clue: '文穗的名字在“阳极之地”名单中，筛选条件与孤儿院居住经历吻合。',
        confirmation: '周德明依据名单选中文穗，将她作为阳极教献祭目标。',
      },
      availability: {
        minCycle: 3,
        locations: ['old-man-building'],
        minSuspicion: { actorId: 'old-man', minimum: 26 },
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'a-lured-inside',
      route: 'A',
      kind: 'event',
      canonicalTruth: '周德明以避雨和提供孤儿院信息为由，将文穗诱入楼内祭坛房。',
      characters: ['fumi', 'old-man'],
      locations: ['old-man-building'],
      revelations: {
        hint: '暴雨中，老人曾邀请一个女孩上楼避雨。',
        clue: '文穗为打听孤儿院往事，接受了周德明上楼喝热水的邀请。',
        confirmation: '周德明以避雨为饵，把文穗诱入藏有祭坛的内室。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredClueIds: ['a-sacrifice-list'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'a-murder-staged-fall',
      route: 'A',
      kind: 'solution',
      canonicalTruth: '周德明完成仪式后将文穗从二楼推下，伪装成暴雨天意外坠亡。',
      characters: ['fumi', 'old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '所谓雨天坠亡现场存在人为布置感。',
        hint: '坠落并不完全符合失足，楼内才是事件的起点。',
        clue: '楼内仪式痕迹与楼后坠落现场属于同一条证据链。',
        confirmation: '周德明完成献祭后将文穗推下二楼，并伪装成意外坠亡。',
      },
      availability: {
        minCycle: 5,
        locations: ['old-man-building'],
        requiredClueIds: ['a-sacrifice-list', 'a-lured-inside'],
        minSuspicion: { actorId: 'old-man', minimum: 50 },
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'b-water-tower-blood',
      route: 'B',
      kind: 'evidence',
      canonicalTruth: '水塔基座残留被雨冲淡的血迹，说明文穗先在水塔受致命撞击。',
      characters: ['fumi', 'detective-a'],
      locations: ['water-tower'],
      revelations: {
        atmosphere: '水塔铁件缝隙里有雨水没能冲净的深色痕迹。',
        hint: '痕迹疑似血迹，位置与公开的坠亡地点不一致。',
        clue: '水塔基座的血迹说明文穗在尸体被发现之前已于此受伤。',
      },
      availability: {
        minCycle: 3,
        locations: ['water-tower'],
        minSuspicion: { actorId: 'detective-a', minimum: 26 },
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'b-detective-coverup',
      route: 'B',
      kind: 'event',
      canonicalTruth: '赵刚强行约谈造成文穗撞击死亡，林静随后指挥移尸至观景台并伪造坠亡。',
      characters: ['fumi', 'detective-a', 'detective-b'],
      locations: ['water-tower', 'observation-deck', 'detective-inn'],
      revelations: {
        hint: '赵刚事后慌乱，林静却立即开始处理通讯和行程记录。',
        clue: '两名侦探的通讯记录把水塔冲突与观景台伪造现场连接起来。',
        confirmation: '赵刚失手致死，林静指挥移尸并伪装成雨天坠亡。',
      },
      availability: {
        minCycle: 4,
        locations: ['detective-inn', 'observation-deck', 'water-tower'],
        requiredClueIds: ['b-water-tower-blood'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'b-accidental-killing',
      route: 'B',
      kind: 'solution',
      canonicalTruth: '赵刚奉生父之命强行带走文穗；挣扎中她撞上水塔铁件死亡，并非预谋杀人。',
      characters: ['fumi', 'detective-a'],
      locations: ['water-tower'],
      revelations: {
        hint: '致命伤更像一次失控冲突，而非预先设计的杀法。',
        clue: '抓痕、衣物纤维和撞击点共同指向赵刚与文穗发生过近身冲突。',
        confirmation: '赵刚强行带走文穗时造成她撞上铁件死亡，随后参与掩盖。',
      },
      availability: {
        minCycle: 5,
        requiredClueIds: ['b-water-tower-blood', 'b-detective-coverup'],
        minSuspicion: { actorId: 'detective-a', minimum: 50 },
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'c-player-made-leave-call',
      route: 'C',
      kind: 'evidence',
      canonicalTruth: '玩家在解离状态下替已经死亡的文穗向学校请假，之后不记得自己打过电话。',
      characters: ['player', 'fumi'],
      locations: ['home', 'school'],
      revelations: {
        atmosphere: '电话记录中的时间与你的记忆无法对上。',
        hint: '请假电话来自与你有关的号码。',
        clue: '通话记录和门卫证词都表明，替文穗请假的男性就是玩家。',
        confirmation: '玩家在解离状态下替已死的文穗请假，并遗忘了这次通话。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'school', 'community-hospital'],
        requiredClueIds: ['shared-male-leave-call'],
        minSuspicion: { actorId: 'self', minimum: 30 },
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'c-loop-is-reenactment',
      route: 'C',
      kind: 'motive',
      canonicalTruth: '所谓轮回是玩家对前一日跟踪路线与创伤记忆的强迫性重演，并非客观时间倒流。',
      characters: ['player', 'fumi'],
      locations: ['home', 'community-hospital'],
      revelations: {
        atmosphere: '每天重复的细节更像记忆误差，而非世界真的复原。',
        hint: '你寻找文穗的路线，与一段被封锁的跟踪记忆高度重合。',
        clue: '时间锚点与病历说明，“轮回”发生在玩家的创伤记忆中。',
        confirmation: '轮回是玩家解离后对前一日跟踪与杀人经历的强迫性重演。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'community-hospital'],
        minSuspicion: { actorId: 'self', minimum: 40 },
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'c-player-killed-fumi',
      route: 'C',
      kind: 'solution',
      canonicalTruth: '前夜玩家因嫉妒和控制欲质问文穗，失控扼住她的脖子导致窒息死亡，随后解离并封锁记忆。',
      characters: ['player', 'fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '家中有一段你无法靠近的夜晚记忆。',
        hint: '文穗并不是在你醒来后才失踪的。',
        clue: '伤痕、碎信与时间记录共同指向前夜发生在家中的暴力。',
        confirmation: '玩家前夜失控扼死文穗，随后解离并将杀人记忆封锁。',
      },
      availability: {
        minCycle: 5,
        locations: ['home'],
        requiredClueIds: ['c-player-made-leave-call', 'c-loop-is-reenactment'],
        minSuspicion: { actorId: 'self', minimum: 50 },
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'none-letter-bedroom',
      route: 'NONE',
      kind: 'evidence',
      canonicalTruth: '文穗把告别信第一片藏在卧室夹层，写着她准备离开贵阳寻找自己的出身。',
      characters: ['fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '抽屉夹层里卡着一角被撕开的纸。',
        hint: '碎纸上的笔迹属于文穗，内容提到“离开这里”。',
        clue: '第一片告别信说明，文穗主动计划离开贵阳，去寻找自己的出身。',
      },
      availability: {
        minCycle: 2,
        locations: ['home'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'none-letter-water-tower',
      route: 'NONE',
      kind: 'evidence',
      canonicalTruth: '文穗把告别信第二片留在水塔笔记中，说明离开不是逃避玩家，而是希望将来能以独立的人回来。',
      characters: ['fumi'],
      locations: ['water-tower'],
      revelations: {
        atmosphere: '水塔笔记本的装订线里夹着另一片相同纸张。',
        hint: '第二片信否认了“逃离你”，却没有写完真正的理由。',
        clue: '第二片告别信写道：“不是逃离你，是去成为能回来见你的人。”',
      },
      availability: {
        minCycle: 3,
        locations: ['water-tower'],
        requiredClueIds: ['none-letter-bedroom'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'none-letter-door-gap',
      route: 'NONE',
      kind: 'evidence',
      canonicalTruth: '文穗把告别信最后一片塞在玩家公寓门缝，记录她要在离开前最后去观景台看一次城市。',
      characters: ['fumi', 'player'],
      locations: ['home', 'observation-deck'],
      revelations: {
        atmosphere: '门垫下粘着一片被雨水泡皱的纸。',
        hint: '最后一片纸提到“最后看一眼这座城市”。',
        clue: '最后一片告别信补全了行程：文穗离开前要去观景台最后看一次贵阳。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'observation-deck'],
        requiredClueIds: ['none-letter-bedroom', 'none-letter-water-tower'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'none-accidental-goodbye',
      route: 'NONE',
      kind: 'solution',
      canonicalTruth: '文穗没有被任何人谋杀；她按计划告别并离开，暴雨中的坠亡是一场意外，玩家追逐的凶手只是拒绝接受告别的执念。',
      characters: ['fumi', 'player'],
      locations: ['water-tower', 'observation-deck'],
      revelations: {
        hint: '完整行程里没有任何一次必须由“凶手”解释的空白。',
        clue: '三片信和完整行程共同表明，文穗主动告别，而坠亡更符合暴雨中的意外。',
        confirmation: '没有凶手：文穗在离开前意外坠亡，玩家始终不肯接受的是那场没说出口的告别。',
      },
      availability: {
        minCycle: 5,
        locations: ['water-tower', 'observation-deck'],
        requiredClueIds: ['none-letter-bedroom', 'none-letter-water-tower', 'none-letter-door-gap'],
        minTripProgress: 100,
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'fake-body-mismatch',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '社区医院记录中的遗体身高与旧伤特征和文穗的医疗记录不符，死者身份并未被可靠确认。',
      characters: ['fumi'],
      locations: ['community-hospital'],
      revelations: {
        atmosphere: '遗体记录与既往病历之间有两处被草草划掉的差异。',
        hint: '身高和旧伤位置都与文穗的记录对不上。',
        clue: '医院记录证明，被认作文穗的遗体在身高与旧伤特征上均不匹配。',
      },
      availability: {
        minCycle: 3,
        locations: ['community-hospital'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-alias-ticket',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '文穗提前购买了死亡次日出发的假名长途车票，并将存根藏在卧室夹层。',
      characters: ['fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '卧室夹层里有一张被刻意刮花姓名的票据。',
        hint: '票据日期在文穗“死亡”之后，姓名也不是她的本名。',
        clue: '假名长途车票将在死亡次日发车，说明文穗提前准备了离城身份。',
      },
      availability: {
        minCycle: 3,
        locations: ['home'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-empty-savings',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '文穗在失踪前一周分批取空了打工积蓄，并通过便利店代收点领取现金和旅行用品。',
      characters: ['fumi'],
      locations: ['supermarket'],
      revelations: {
        atmosphere: '便利店代收记录里连续出现了同一个模糊签名。',
        hint: '文穗在失踪前分批取走积蓄，还领取了旅行用品。',
        clue: '取款与代收记录表明，文穗提前准备了足以离城生活的现金和用品。',
      },
      availability: {
        minCycle: 3,
        locations: ['supermarket'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-postdeath-sighting',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '一名车站工作人员在官方死亡时间之后见过与文穗外形一致、穿雨衣的女孩搭乘离城班车。',
      characters: ['fumi'],
      locations: ['observation-deck', 'mountain-trail'],
      revelations: {
        atmosphere: '死亡时间之后的车站记录里，有一个熟悉的雨衣背影。',
        hint: '工作人员记得一个与文穗相似的女孩独自登上离城班车。',
        clue: '车站证词和时间记录确认，官方死亡时间之后仍有人见到文穗外形的女孩离城。',
      },
      availability: {
        minCycle: 4,
        locations: ['observation-deck', 'mountain-trail'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-touko-request',
      route: 'FAKE',
      kind: 'npc-knowledge',
      canonicalTruth: '文穗事先请求灯织在玩家追问时谎称她已经死亡，以保护逃离计划。',
      characters: ['fumi', 'touko'],
      locations: ['senpai-building'],
      revelations: {
        hint: '灯织答应过文穗，要替她保守一个会让玩家受伤的秘密。',
        clue: '灯织复述了文穗的托付：“如果他问起我，就说我死了。”',
      },
      availability: {
        minCycle: 4,
        locations: ['senpai-building'],
        minAffinity: { actorId: 'touko', minimum: 80 },
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-staged-death-escape',
      route: 'FAKE',
      kind: 'solution',
      canonicalTruth: '文穗利用暴雨、身份不明的遗体与伪造痕迹策划假死，躲避生父派来的人并逃离贵阳。',
      characters: ['fumi'],
      locations: ['observation-deck', 'water-tower'],
      revelations: {
        hint: '所有异常都指向同一个被忽略的前提：文穗可能没有死。',
        clue: '尸源、车票、现金与死后目击构成了提前策划的离城证据链。',
        confirmation: '文穗策划假死并逃离贵阳；她用“死亡”换取自由，也在等待玩家是否会放手。',
      },
      availability: {
        minCycle: 5,
        locations: ['observation-deck', 'water-tower'],
        requiredKnownFactSet: {
          factIds: [
            'fake-body-mismatch',
            'fake-alias-ticket',
            'fake-empty-savings',
            'fake-postdeath-sighting',
            'fake-touko-request',
          ],
          minimum: 3,
        },
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'cult-symbol-sun-room',
      route: 'CULT',
      kind: 'evidence',
      canonicalTruth: '周德明祭坛上的符号与孤儿院“太阳房”壁画同源，属于真实运作的阳极教仪式系统。',
      characters: ['old-man', 'fumi'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '祭坛纹样与你见过的孤儿院旧壁画有异常相似之处。',
        hint: '两组符号的缺口和排列完全一致，不像偶然模仿。',
        clue: '祭坛符号与孤儿院“太阳房”壁画属于同一套阳极教仪式图式。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-rain-death-pattern',
      route: 'CULT',
      kind: 'evidence',
      canonicalTruth: '阳极名单中的多名旧孤儿均死于暴雨日的所谓意外，死亡日期构成持续多年的献祭规律。',
      characters: ['old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '名单边缘记着一串年份与天气符号。',
        hint: '名单上已经划掉的人，全都死在暴雨天。',
        clue: '旧档案确认，名单中的多名孤儿都在暴雨日死于被归为意外的事件。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-old-man-ageless',
      route: 'CULT',
      kind: 'npc-knowledge',
      canonicalTruth: '周德明二十年来外貌几乎没有衰老，附近旧居民能够确认这一反常现象。',
      characters: ['old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '旧合照里的老人和现在几乎没有差别。',
        hint: '邻居说，周德明二十年来“连皱纹的位置都没变”。',
        clue: '跨越二十年的照片与居民证词共同证明，周德明没有正常衰老。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-old-man-remembers-loop',
      route: 'CULT',
      kind: 'npc-knowledge',
      canonicalTruth: '周德明保留上一轮的记忆，并知道玩家正在重复9月9日。',
      characters: ['old-man', 'player'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '老人对你还没做过的动作提前偏了偏头。',
        hint: '周德明说出只有上一轮的你才讲过的话。',
        clue: '老人明确记得上一轮会面，知道玩家正在重复同一天。',
      },
      availability: {
        minCycle: 5,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        requiredAnyClueIds: ['cult-symbol-sun-room', 'cult-rain-death-pattern', 'cult-old-man-ageless'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-sacrifice-powers-loop',
      route: 'CULT',
      kind: 'solution',
      canonicalTruth: '献祭确实有效；文穗未被完全吸收的阳寿缠绕在玩家的执念上，形成不断重演的9月9日。',
      characters: ['fumi', 'old-man', 'player'],
      locations: ['old-man-building'],
      revelations: {
        hint: '轮回与祭坛不是同时出现的巧合。',
        clue: '仪式残卷把“未尽阳寿”描述为会依附最强执念而重复死亡之日。',
        confirmation: '献祭真实有效，文穗溢出的阳寿依附玩家，制造了不断重演的暴雨日。',
      },
      availability: {
        minCycle: 5,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        requiredKnownFactSet: {
          factIds: [
            'cult-symbol-sun-room',
            'cult-rain-death-pattern',
            'cult-old-man-ageless',
            'cult-old-man-remembers-loop',
          ],
          minimum: 3,
        },
        requiresOverlayLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'psych-receipt-year-drift',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '便利店小票都标记为9月9日，但年份彼此不同，说明重复的并非同一个现实日期。',
      characters: ['player'],
      locations: ['supermarket'],
      revelations: {
        atmosphere: '几张相同日期的小票，纸张老化程度却完全不同。',
        hint: '小票都是9月9日，年份却相差数年。',
        clue: '连续“轮回”留下的小票年份不同，当前世界无法是同一天的客观重置。',
      },
      availability: {
        minCycle: 4,
        locations: ['supermarket'],
        requiredBaseRoute: 'C',
        maxSanity: 40,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-doctor-badge',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '社区医院里被当作普通值班人员的角色实际佩戴玩家主治医师胸牌，并熟悉玩家的病情。',
      characters: ['player'],
      locations: ['community-hospital'],
      revelations: {
        atmosphere: '医生胸牌被白大褂边缘遮住了一半。',
        hint: '胸牌上不是“值班医生”，而是“主治医师”。',
        clue: '医生是玩家的主治医师，并把这次调查称作“又一次走远”。',
      },
      availability: {
        minCycle: 4,
        locations: ['community-hospital'],
        requiredBaseRoute: 'C',
        maxSanity: 40,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-window-without-street',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '玩家公寓的窗从任何角度都看不到应存在的街道，因为它其实是病房内室的窗。',
      characters: ['player'],
      locations: ['home'],
      revelations: {
        atmosphere: '无论站到窗边哪个角度，楼下都只有一片没有纵深的灰。',
        hint: '按建筑位置本应可见的街道从窗外消失了。',
        clue: '窗户的方位与外部地图不可能同时成立，这个“公寓”并不是现实中的房间。',
      },
      availability: {
        minCycle: 4,
        locations: ['home'],
        requiredBaseRoute: 'C',
        maxSanity: 35,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-medication-label',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '药瓶标签被撕掉的部分写着“每日两次，不可自行停药”，玩家正在药物减量后发作。',
      characters: ['player'],
      locations: ['home', 'community-hospital'],
      revelations: {
        atmosphere: '枕头下压着半张与药瓶撕口完全吻合的标签。',
        hint: '标签写着“每日两次”，后面还有一句警告。',
        clue: '完整标签是“每日两次，不可自行停药”，而玩家已经停药。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'community-hospital'],
        requiredBaseRoute: 'C',
        maxSanity: 30,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-investigation-is-episode',
      route: 'PSYCH',
      kind: 'solution',
      canonicalTruth: '整场调查是玩家停药后的一次精神病性发作；文穗早已在多年前的意外中死亡，NPC与轮回是病房经验和丧失感的象征重组。',
      characters: ['player', 'fumi', 'old-man', 'touko'],
      locations: ['community-hospital'],
      revelations: {
        hint: '“你杀了文穗”也可能只是内室用来保护更深丧失的一层故事。',
        clue: '年份、病房结构、主治医师与药物记录共同指向一次长期治疗中的发作。',
        confirmation: '调查世界是停药后的发作：文穗早已因意外去世，人物与轮回是病房经验的重组。',
      },
      availability: {
        minCycle: 5,
        locations: ['community-hospital'],
        requiredBaseRoute: 'C',
        maxSanity: 20,
        requiredKnownFactSet: {
          factIds: [
            'psych-receipt-year-drift',
            'psych-doctor-badge',
            'psych-window-without-street',
            'psych-medication-label',
          ],
          minimum: 3,
        },
        requiresOverlayLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
  ],
  npcKnowledge: [
    { npcId: 'school-guard', factId: 'shared-school-absence', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'school-guard', factId: 'shared-male-leave-call', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'morning-witness', factId: 'shared-detective-tail', maxRevealLevel: 'hint', stance: 'knows' },
    { npcId: 'touko', factId: 'shared-water-tower-secret', maxRevealLevel: 'hint', stance: 'suspects' },
    { npcId: 'old-man', factId: 'a-sacrifice-list', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'old-man', factId: 'a-lured-inside', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'shared-detective-tail', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'b-water-tower-blood', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'b-accidental-killing', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-b', factId: 'b-detective-coverup', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'touko', factId: 'fake-touko-request', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'old-man', factId: 'cult-old-man-remembers-loop', maxRevealLevel: 'clue', stance: 'lies-about' },
  ],
};
