import type { MysteryTruthGraph } from './types';
import { FAKE_PREPARATION_FACTS, ROUTE_CAUSAL_FACTS, ROUTE_SUPPORT_FACTS, SOLUTION_FACTS } from '../../engine/story-rules';
import { ITINERARY_FACT_IDS } from './itinerary';

/**
 * 剧情正典的唯一事实源。canonicalTruth 只能留在事实层，不能直接传给编剧。
 * revelation 文本按“氛围 → 暗示 → 线索 → 确认”逐层增加信息量。
 */
export const MYSTERY_TRUTH_GRAPH: MysteryTruthGraph = {
  version: '2026-09-15.1',
  facts: [
    {
      id: 'shared-apron-missing',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '绿色围裙不在惯常存放处；文穗事前物品清单把围裙列入外出用品。材料未记实际取走时间，不能证明她在本日离家。',
      characters: ['fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '衣柜里有一处不自然的空缺。',
        hint: '文穗常穿的绿色围裙不在衣柜里。',
        clue: '衣柜里没有绿色围裙，文穗事前清单把它列为外出用品；清单没有取走时间，不能据此认定她今天穿校服离家。',
      },
      availability: { minCycle: 1, locations: ['home'] },
    },
    {
      id: 'shared-school-absence',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '学校本日考勤无文穗入校记录，门卫值班簿有一条相似校服女孩自称请假的记载；这条记载未核对证件，页上日期有补写痕迹。',
      characters: ['fumi', 'school-guard'],
      locations: ['school'],
      revelations: {
        atmosphere: '门卫翻到一条校服女孩在门口询问请假的记载。',
        hint: '考勤没有文穗入校记录；门卫记得一个相似的女孩，但当时没有核对身份。',
        clue: '本日考勤没有文穗入校记录；门卫值班簿写过一名相似校服女孩自称已请假，但日期为事后补写且未验身份，不能确认是文穗本日到场。',
      },
      availability: { minCycle: 1, locations: ['school'] },
    },
    {
      id: 'shared-male-leave-call',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '学校的请假录音中是一名男性声音；来电登记为文穗请假，录音本身不能确定拨打者身份或她当时状况。',
      characters: ['player', 'school-guard'],
      locations: ['school', 'home'],
      revelations: {
        atmosphere: '请假记录里有一个说不通的小细节。',
        hint: '请假电话不是文穗本人打的。',
        clue: '学校登记把一段男性声音的来电记为替文穗请假；录音可核对来电号码和时间，尚不能确定拨打者身份或文穗当时状况。',
      },
      availability: { minCycle: 2, locations: ['school'] },
    },
    {
      id: 'shared-nurse-school-inquiry',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '学校本日来访登记记有一名挂社区医院临时工牌的女人询问文穗；登记与工牌编号核对为林静，未记录她见到文穗。',
      characters: ['fumi', 'detective-b', 'school-guard'],
      locations: ['school'],
      revelations: {
        atmosphere: '门卫找到另一条来访问询登记。',
        hint: '一名挂社区医院临时工牌的女人来问文穗是否进校，门卫没有提供本人到场的证据。',
        clue: '本日来访登记与工牌编号对照表明，询问文穗行踪的人是林静；登记只证明林静来问过，不能证明她或门卫本日见到文穗。',
      },
      availability: { minCycle: 2, locations: ['school'] },
      suspicionTargets: ['detective-b'],
    },
    {
      id: 'shared-water-tower-secret',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '废弃水塔是文穗的秘密据点，她在此调查自己的孤儿院身世。',
      characters: ['fumi'],
      locations: ['water-tower'],
      revelations: {
        atmosphere: '水塔里残留着长期有人活动的痕迹。',
        hint: '刻痕、零食袋和耗尽的电池都属于同一个常客。',
        clue: '笔记与墙上刻痕表明，这里是文穗调查自己身世的秘密据点。',
        confirmation: '文穗多次来水塔整理孤儿院、院长与生父相关资料。',
      },
      availability: { minCycle: 2, locations: ['water-tower'] },
    },
    {
      id: 'shared-detective-tail',
      route: 'shared',
      kind: 'evidence',
      canonicalTruth: '晨练者记得赵刚跟在相似校服女孩后沿山路前行；证词未核对女孩身份，手写记录只写雨天上午，原始影像与日期仍待核对。',
      characters: ['fumi', 'detective-a', 'morning-witness'],
      locations: ['mountain-trail'],
      revelations: {
        atmosphere: '晨练者的记录里有两个一前一后的雨中身影。',
        hint: '证人把后面的寸头男人认作赵刚，却只看清前面女孩的校服。',
        clue: '晨练者认出后方男人是赵刚，前方女孩穿着与文穗相似的校服；记录只写“雨天上午”，尚未核对日期与女孩身份，不能确认文穗本日被尾随。',
      },
      availability: { minCycle: 2, locations: ['mountain-trail'] },
      suspicionTargets: ['detective-a'],
    },
    {
      id: 'red-herring-part-time-job',
      route: 'shared',
      kind: 'red-herring',
      canonicalTruth: '围裙与请假容易使玩家误以为文穗秘密打工，但这不是她失踪的根因。',
      characters: ['fumi'],
      locations: ['home', 'supermarket'],
      revelations: {
        hint: '围裙被列为外出用品，让你猜她是否准备去做临时工作；这只是猜测，不能当成去向。',
      },
      availability: { minCycle: 1 },
      suspicionTargets: ['clerk'],
    },
    {
      id: 'a-sacrifice-list',
      route: 'A',
      kind: 'evidence',
      canonicalTruth: '周德明持有“阳极之地”名单，文穗因在孤儿院生活超过三年而被列为献祭目标。',
      characters: ['fumi', 'old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '老人内室里有被刻意藏起的名单。',
        hint: '名单把孤儿院称作“至阳之地”，其中一个名字与文穗有关。',
        clue: '文穗的名字在“阳极之地”名单中，筛选条件与孤儿院居住经历吻合。',
        confirmation: '周德明依据名单选中文穗，将她作为阳极教献祭目标。',
      },
      availability: {
        minCycle: 3,
        locations: ['old-man-building'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['old-man'],
    },
    {
      id: 'a-lured-inside',
      route: 'A',
      kind: 'event',
      canonicalTruth: '周德明以避雨和提供孤儿院信息为由，将文穗诱入楼内祭坛房。',
      characters: ['fumi', 'old-man'],
      locations: ['old-man-building'],
      revelations: {
        hint: '老人承认，他曾以避雨和旧档案为由邀请女孩上楼。',
        clue: '周德明发出的邀请写着“上楼避雨，内室有孤儿院旧档案”，邻居也记得类似招呼；材料尚不能确认文穗实际进入内室的日期与经过。',
        confirmation: '周德明发出了以避雨和孤儿院档案为由的内室邀请；实际进入与随后发生的事仍须现场证据核对。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredClueIds: ['a-sacrifice-list'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['old-man'],
    },
    {
      id: 'a-murder-staged-fall',
      route: 'A',
      kind: 'solution',
      canonicalTruth: '周德明在内室对文穗实施控制性暴力后将她从二楼推下，再沿楼后通道转移到观景台边坡伪装成失足坠亡。',
      characters: ['fumi', 'old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '所谓雨天坠亡现场存在人为布置感。',
        hint: '坠落并不完全符合失足，楼内才是事件的起点。',
        clue: '楼内仪式痕迹与楼后坠落现场属于同一条证据链。',
        confirmation: '邀请与名单说明周德明如何选中并诱入文穗；伤情、窗槽纤维和转运记录证明他在内室施暴、将她推下二楼，再移至观景台边坡伪装失足。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        locations: ['old-man-building'],
        requiredClueIds: [...ROUTE_SUPPORT_FACTS.A, ...ROUTE_CAUSAL_FACTS.A],
        requiresRouteLock: true,
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['old-man'],
    },
    {
      id: 'b-water-tower-blood',
      route: 'B',
      kind: 'evidence',
      canonicalTruth: '水塔基座残留被雨冲淡的血迹，说明文穗先在水塔受致命撞击。',
      characters: ['fumi', 'detective-a'],
      locations: ['water-tower'],
      revelations: {
        atmosphere: '水塔铁件缝隙里有雨水没能冲净的深色痕迹。',
        hint: '铁件缝隙中的痕迹疑似血迹，采样编号可供后续核验来源与留存时间。',
        clue: '水塔基座样本初筛含血液成分，但归属和留存时间尚未鉴定；它提供待核对的受伤地点，不能据此认定文穗在这里受伤。',
      },
      availability: {
        minCycle: 3,
        locations: ['water-tower'],
        maxRevealBeforeRouteLock: 'clue',
      },
      suspicionTargets: ['detective-a'],
    },
    {
      id: 'b-detective-coverup',
      route: 'B',
      kind: 'event',
      canonicalTruth: '赵刚强行约谈造成文穗撞击死亡，林静随后指挥移尸至观景台并伪造坠亡。',
      characters: ['fumi', 'detective-a', 'detective-b'],
      locations: ['water-tower', 'observation-deck', 'detective-inn'],
      revelations: {
        hint: '赵刚与林静的通讯中出现了水塔、车辆与改动行程的词句。',
        clue: '两人的通讯记录含“水塔碰头”“车开到观景台”“原记录别用了”；号码已核对，但对象与运送物不明，不能仅凭这些词句认定致死或移尸。',
        confirmation: '通讯原始记录确认赵刚和林静协调了水塔、车辆及观景台行程，但致命接触与转移对象必须另以伤情和车辆原始影像核实。',
      },
      availability: {
        minCycle: 4,
        locations: ['detective-inn', 'observation-deck', 'water-tower'],
        requiredClueIds: ['b-water-tower-blood'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['detective-a', 'detective-b'],
    },
    {
      id: 'b-accidental-killing',
      route: 'B',
      kind: 'solution',
      canonicalTruth: '赵刚奉生父之命强行带走文穗；挣扎中她撞上水塔铁件死亡，并非预谋杀人。',
      characters: ['fumi', 'detective-a'],
      locations: ['water-tower'],
      revelations: {
        hint: '致命伤更像一次失控冲突，而非预先设计的杀法。',
        clue: '抓痕、衣物纤维和撞击点共同指向赵刚与文穗发生过近身冲突。',
        confirmation: '赵刚强行带走文穗时造成她撞上铁件死亡，随后参与掩盖。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        requiredClueIds: [...ROUTE_SUPPORT_FACTS.B, ...ROUTE_CAUSAL_FACTS.B],
        requiresRouteLock: true,
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['detective-a'],
    },
    {
      id: 'c-player-made-leave-call',
      route: 'C',
      kind: 'evidence',
      canonicalTruth: '玩家在解离状态下替已经死亡的文穗向学校请假，之后不记得自己打过电话。',
      characters: ['player', 'fumi'],
      locations: ['home', 'school'],
      revelations: {
        atmosphere: '电话记录中的时间与你的记忆无法对上。',
        hint: '请假电话来自与你有关的号码。',
        clue: '家庭号码账单、学校录音与玩家留存语音相符，证明请假来电由玩家拨出；这只证明通话，不能证明文穗已死或玩家施暴。',
        confirmation: '号码账单和录音核对确认请假来电由玩家拨出；他不记得通话，这一差异不能证明文穗的死亡时间或死亡原因。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'school', 'community-hospital'],
        requiredClueIds: ['shared-male-leave-call'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['self'],
    },
    {
      id: 'c-loop-is-reenactment',
      route: 'C',
      kind: 'motive',
      canonicalTruth: '所谓轮回是玩家对前一日跟踪路线与创伤记忆的强迫性重演，并非客观时间倒流。',
      characters: ['player', 'fumi'],
      locations: ['home', 'community-hospital'],
      revelations: {
        atmosphere: '病历与个人时间记录里，对同一段经历出现了不同描述。',
        hint: '你反复画出的调查路线，与事前留下的路线草稿重合。',
        clue: '路线草稿、日记与治疗记录出现重复的时间断片，支持调查包含记忆重演的解释；这些材料本身不能证明施暴，也不能单独断定整个外界都是幻觉。',
        confirmation: '外部案卷已独立确认前夜暴力；与治疗时间表对照后，反复调查被确认为玩家对案发前经历的记忆重演，病历并不是定罪依据。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'community-hospital'],
        requiresRouteLock: true,
        requiredClueIds: ['c-night-gap-record'],
        maxRevealBeforeRouteLock: 'clue',
        maxRevealAfterRouteLock: 'clue',
      },
      suspicionTargets: ['self'],
    },
    {
      id: 'c-player-killed-fumi',
      route: 'C',
      kind: 'solution',
      canonicalTruth: '前夜玩家因嫉妒和控制欲质问文穗，失控扼住她的脖子导致窒息死亡，随后解离并封锁记忆。',
      characters: ['player', 'fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '家中有一段你无法靠近的夜晚记忆。',
        hint: '文穗并不是在你醒来后才失踪的。',
        clue: '伤痕、碎信与时间记录共同指向前夜发生在家中的暴力。',
        confirmation: '玩家前夜失控扼死文穗，随后解离并将杀人记忆封锁。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        locations: ['home'],
        requiredClueIds: [...ROUTE_SUPPORT_FACTS.C, ...ROUTE_CAUSAL_FACTS.C],
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
      suspicionTargets: ['self'],
    },
    {
      id: 'none-letter-bedroom',
      route: 'NONE',
      kind: 'evidence',
      canonicalTruth: '文穗把告别信第一片藏在卧室夹层，写着她准备离开贵阳寻找自己的出身。',
      characters: ['fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '抽屉夹层里卡着一角被撕开的纸。',
        hint: '碎纸上的笔迹属于文穗，内容提到“离开这里”。',
        clue: '第一片告别信说明，文穗主动计划离开贵阳，去寻找自己的出身。',
      },
      availability: {
        minCycle: 2,
        locations: ['home'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'none-letter-water-tower',
      route: 'NONE',
      kind: 'evidence',
      canonicalTruth: '文穗把告别信第二片留在水塔笔记中，说明离开不是逃避玩家，而是希望将来能以独立的人回来。',
      characters: ['fumi'],
      locations: ['water-tower'],
      revelations: {
        atmosphere: '水塔笔记本的装订线里夹着另一片相同纸张。',
        hint: '第二片信否认了“逃离你”，却没有写完真正的理由。',
        clue: '第二片告别信写道：“不是逃离你，是去成为能回来见你的人。”',
      },
      availability: {
        minCycle: 3,
        locations: ['water-tower'],
        requiredClueIds: ['none-letter-bedroom'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'none-letter-door-gap',
      route: 'NONE',
      kind: 'evidence',
      canonicalTruth: '文穗把告别信最后一片塞在玩家公寓门缝，记录她要在离开前最后去观景台看一次城市。',
      characters: ['fumi', 'player'],
      locations: ['home', 'observation-deck'],
      revelations: {
        atmosphere: '门垫下粘着一片被雨水泡皱的纸。',
        hint: '最后一片纸提到“最后看一眼这座城市”。',
        clue: '最后一片告别信补全了行程：文穗离开前要去观景台最后看一次贵阳。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'observation-deck'],
        requiredClueIds: ['none-letter-bedroom', 'none-letter-water-tower'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'none-accidental-goodbye',
      route: 'NONE',
      kind: 'solution',
      canonicalTruth: '文穗没有被任何人谋杀；她按计划告别并离开，暴雨中的坠亡是一场意外，玩家追逐的凶手只是拒绝接受告别的执念。',
      characters: ['fumi', 'player'],
      locations: ['water-tower', 'observation-deck'],
      revelations: {
        hint: '完整行程里没有任何一次必须由“凶手”解释的空白。',
        clue: '三片信证明离开意愿；独行原始录像、栏杆检修记录和伤情另行对应，才支持她在告别前失足坠亡。',
        confirmation: '文穗自主准备离开，独行录像记录了湿滑处踩空和栏杆断裂，现场与伤情排除他人接触致伤；她在观景台意外坠亡，离开意愿本身从来不是死因证据。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        locations: ['water-tower', 'observation-deck'],
        requiredClueIds: [...ROUTE_SUPPORT_FACTS.NONE, ...ROUTE_CAUSAL_FACTS.NONE, ...ITINERARY_FACT_IDS],
        minTripProgress: 100,
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'fake-body-mismatch',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '初报转录表的身高与旧伤栏同既往病历不符，表上未附验身签名与原始测量；只能发现初报身份认定程序有漏洞，不能提前断定遗体是谁。',
      characters: ['fumi'],
      locations: ['community-hospital'],
      revelations: {
        atmosphere: '初报转录表的两处修改没有核验签名。',
        hint: '初报的身高和旧伤栏与病历不一致，原始测量表还没有附上。',
        clue: '初报转录表中的身高、旧伤栏与文穗病历不一致，且缺验身签名；应追查原始鉴定，转录差异尚不能证明遗体不是文穗。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 3,
        locations: ['community-hospital'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-alias-ticket',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '文穗提前购买了9月10日出发的化名长途车票，并将存根藏在卧室夹层；准备车票不证明实际登车。',
      characters: ['fumi'],
      locations: ['home'],
      revelations: {
        atmosphere: '卧室夹层里有一张被刻意刮花姓名的票据。',
        hint: '票据发车日期是9月10日，姓名也不是她的本名。',
        clue: '车票存根的发车日期为9月10日、姓名使用化名，说明文穗事前准备了离城安排；票据本身不能证明她后来登车。',
      },
      availability: {
        minCycle: 3,
        locations: ['home'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-empty-savings',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '文穗在失踪前一周分批取空了打工积蓄，并通过便利店代收点领取现金和旅行用品。',
      characters: ['fumi'],
      locations: ['supermarket'],
      revelations: {
        atmosphere: '便利店代收记录里连续出现了同一个模糊签名。',
        hint: '文穗在失踪前分批取走积蓄，还领取了旅行用品。',
        clue: '取款与代收记录表明，文穗提前准备了足以离城生活的现金和用品。',
      },
      availability: {
        minCycle: 3,
        locations: ['supermarket'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-postdeath-sighting',
      route: 'FAKE',
      kind: 'evidence',
      canonicalTruth: '车站工作人员记下初报发送之后一名相似雨衣女孩登车，班次时钟可核对，但未验身份证件。',
      characters: ['fumi'],
      locations: ['observation-deck', 'mountain-trail'],
      revelations: {
        atmosphere: '初报发送之后的车站记录里，有一个熟悉的雨衣背影。',
        hint: '工作人员记得一个与文穗相似的女孩独自登上离城班车。',
        clue: '班次记录核实相似雨衣女孩在16:00初报发送后登车；工作人员未验身份，不能只凭外形确认是文穗，也不能把通报时刻当成死亡时刻。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 4,
        locations: ['observation-deck', 'mountain-trail'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-touko-request',
      route: 'FAKE',
      kind: 'npc-knowledge',
      canonicalTruth: '文穗事前只请求灯织代存小包与转交报平安约定，不准透露目的地；灯织在初报后收到约定訊息才知道误认可能被用来遮掩离开。',
      characters: ['fumi', 'touko'],
      locations: ['senpai-building'],
      revelations: {
        hint: '灯织答应替文穗保存一个小包，并且不公开目的地。',
        clue: '灯织出示事前寄存小包与报平安约定：她只帮助保管和转交，不参与尸体或现场布置；她直到初报后收到约定訊息，才知道身份误认可能被用于隐去行踪。',
      },
      availability: {
        minCycle: 4,
        locations: ['senpai-building'],
        minAffinity: { actorId: 'touko', minimum: 80 },
        notBeforeTime: '16:00',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'fake-staged-death-escape',
      route: 'FAKE',
      kind: 'solution',
      canonicalTruth: '文穗自主准备离城，灯织只代存行李并转交联络。初报将无名遗体与遗失物标签错误关联后文穗选择暂不纠正，借误认隐去行踪；独立身份核验确认她离开后仍生还。她从未取得或摆布遗体，公开追寻会让跟踪者追到她。',
      characters: ['fumi'],
      locations: ['observation-deck', 'water-tower'],
      revelations: {
        hint: '所有异常都指向同一个被忽略的前提：文穗可能没有死。',
        clue: '事前准备、初报误认的形成过程和离开后的本人身份核验分别成立，说明文穗借误认保密离城；灯织的协助止于行李和联络。',
        confirmation: '文穗仍活着：初报把无名遗体与遗失物标签错误关联，她离城后利用误认隐去行踪，没有搬动或布置遗体。身份核验确认生还，但公开追查、传播目的地会把追踪者带到她身边。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        locations: ['observation-deck', 'water-tower'],
        requiredClueIds: [...ROUTE_SUPPORT_FACTS.FAKE, ...ROUTE_CAUSAL_FACTS.FAKE],
        requiredAnyClueIds: [...FAKE_PREPARATION_FACTS],
        requiresRouteLock: true,
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'cult-symbol-sun-room',
      route: 'CULT',
      kind: 'evidence',
      canonicalTruth: '周德明祭坛上的符号与孤儿院“太阳房”壁画同源，属于真实运作的阳极教仪式系统。',
      characters: ['old-man', 'fumi'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '祭坛纹样与你见过的孤儿院旧壁画有异常相似之处。',
        hint: '两组符号的缺口和排列完全一致，不像偶然模仿。',
        clue: '祭坛符号与孤儿院“太阳房”壁画属于同一套阳极教仪式图式。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-rain-death-pattern',
      route: 'CULT',
      kind: 'evidence',
      canonicalTruth: '阳极名单中的多名旧孤儿均死于暴雨日的所谓意外，死亡日期构成持续多年的献祭规律。',
      characters: ['old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '名单边缘记着一串年份与天气符号。',
        hint: '名单上已经划掉的人，全都死在暴雨天。',
        clue: '旧档案确认，名单中的多名孤儿都在暴雨日死于被归为意外的事件。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-old-man-ageless',
      route: 'CULT',
      kind: 'npc-knowledge',
      canonicalTruth: '周德明二十年来外貌几乎没有衰老，附近旧居民能够确认这一反常现象。',
      characters: ['old-man'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '旧合照里的老人和现在几乎没有差别。',
        hint: '邻居说，周德明二十年来“连皱纹的位置都没变”。',
        clue: '跨越二十年的照片与居民证词共同证明，周德明没有正常衰老。',
      },
      availability: {
        minCycle: 4,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-old-man-remembers-loop',
      route: 'CULT',
      kind: 'npc-knowledge',
      canonicalTruth: '周德明保留上一轮的记忆，并知道玩家正在重复9月9日。',
      characters: ['old-man', 'player'],
      locations: ['old-man-building'],
      revelations: {
        atmosphere: '老人对你还没做过的动作提前偏了偏头。',
        hint: '周德明说出只有上一轮的你才讲过的话。',
        clue: '老人明确记得上一轮会面，知道玩家正在重复同一天。',
      },
      availability: {
        minCycle: 5,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        requiredAnyClueIds: ['cult-symbol-sun-room', 'cult-rain-death-pattern', 'cult-old-man-ageless'],
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'cult-sacrifice-powers-loop',
      route: 'CULT',
      kind: 'solution',
      canonicalTruth: '献祭确实有效；周德明杀害并转移文穗的事实不变，未被吸收的阳寿依附玩家形成重复的9月9日。残卷与可重复的祭坛反应证实：毁去支点可终止循环；逆接符号则消耗玩家自身余生封存清晨，不能令文穗在世界中复活。',
      characters: ['fumi', 'old-man', 'player'],
      locations: ['old-man-building'],
      revelations: {
        hint: '轮回与祭坛不是同时出现的巧合。',
        clue: '仪式残卷与重复核验的祭坛反应对应：未尽阳寿可依附执念重演一天；毁支点会停止反应，逆接符号会消耗操作者余生维持清晨。它们没有使死者复活的记录。',
        confirmation: '周德明杀害并转移文穗的罪行不变，献祭使她未尽的阳寿依附玩家形成循环。残卷与祭坛试验已验证两种后果：毁去支点终止循环；逆接符号以玩家自身余生封存清晨，文穗仍未复活。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        locations: ['old-man-building'],
        requiredBaseRoute: 'A',
        requiredKnownFactSet: {
          factIds: [
            'cult-symbol-sun-room',
            'cult-rain-death-pattern',
            'cult-old-man-ageless',
            'cult-old-man-remembers-loop',
          ],
          minimum: 3,
        },
        requiresOverlayLock: true,
        requiredConfirmedFactIds: [SOLUTION_FACTS.A],
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'psych-receipt-year-drift',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '便利店小票都标记为9月9日，但年份彼此不同，说明重复的并非同一个现实日期。',
      characters: ['player'],
      locations: ['supermarket'],
      revelations: {
        atmosphere: '几张相同日期的小票，纸张老化程度却完全不同。',
        hint: '小票都是9月9日，年份却相差数年。',
        clue: '连续“轮回”留下的小票年份不同，当前世界无法是同一天的客观重置。',
      },
      availability: {
        minCycle: 4,
        locations: ['supermarket'],
        requiredBaseRoute: 'C',
        maxSanity: 40,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-doctor-badge',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '社区医院里被当作普通值班人员的角色实际佩戴玩家主治医师胸牌，并熟悉玩家的病情。',
      characters: ['player'],
      locations: ['community-hospital'],
      revelations: {
        atmosphere: '医生胸牌被白大褂边缘遮住了一半。',
        hint: '胸牌上不是“值班医生”，而是“主治医师”。',
        clue: '医生是玩家的主治医师，并把这次调查称作“又一次走远”。',
      },
      availability: {
        minCycle: 4,
        locations: ['community-hospital'],
        requiredBaseRoute: 'C',
        maxSanity: 40,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-window-without-street',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '玩家公寓的窗从任何角度都看不到应存在的街道，因为它其实是病房内室的窗。',
      characters: ['player'],
      locations: ['home'],
      revelations: {
        atmosphere: '无论站到窗边哪个角度，楼下都只有一片没有纵深的灰。',
        hint: '按建筑位置本应可见的街道从窗外消失了。',
        clue: '窗户的方位与外部地图不可能同时成立，这个“公寓”并不是现实中的房间。',
      },
      availability: {
        minCycle: 4,
        locations: ['home'],
        requiredBaseRoute: 'C',
        maxSanity: 35,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-medication-label',
      route: 'PSYCH',
      kind: 'evidence',
      canonicalTruth: '药瓶标签被撕掉的部分写着“每日两次，不可自行停药”，玩家正在药物减量后发作。',
      characters: ['player'],
      locations: ['home', 'community-hospital'],
      revelations: {
        atmosphere: '枕头下压着半张与药瓶撕口完全吻合的标签。',
        hint: '标签写着“每日两次”，后面还有一句警告。',
        clue: '完整标签是“每日两次，不可自行停药”，而玩家已经停药。',
      },
      availability: {
        minCycle: 4,
        locations: ['home', 'community-hospital'],
        requiredBaseRoute: 'C',
        maxSanity: 30,
        maxRevealBeforeRouteLock: 'clue',
      },
    },
    {
      id: 'psych-investigation-is-episode',
      route: 'PSYCH',
      kind: 'solution',
      canonicalTruth: '治疗时间表、房间结构与原始案卷的独立对照确认，调查是玩家在治疗环境里对案发前后的重构；文穗仍是被玩家在那次9月9日的前夜在家施暴致死，治疗解释不撤销这项责任，也不以症状证明犯罪。',
      characters: ['player', 'fumi', 'old-man', 'touko'],
      locations: ['community-hospital'],
      revelations: {
        hint: '治疗环境的线索能解释调查为什么反复，却不能抹去已经独立核实的前夜暴力。',
        clue: '年份、病房结构、主治医师与药物记录共同指向一次长期治疗中的发作。',
        confirmation: '治疗时间表与外部案卷共同确认，调查场景重组了治疗环境和案发记忆；文穗仍死于玩家在家中的前夜暴力，治疗能够解释重构，不能撤销死亡与责任。',
      },
      availability: { notBeforeTime: '16:00',
        minCycle: 5,
        locations: ['community-hospital'],
        requiredBaseRoute: 'C',
        maxSanity: 20,
        requiredKnownFactSet: {
          factIds: [
            'psych-receipt-year-drift',
            'psych-doctor-badge',
            'psych-window-without-street',
            'psych-medication-label',
          ],
          minimum: 3,
        },
        requiresOverlayLock: true,
        requiredConfirmedFactIds: [SOLUTION_FACTS.C],
        maxRevealAfterRouteLock: 'confirmation',
      },
    },
    {
      id: 'shared-fumi-boundary-note', route: 'shared', kind: 'evidence',
      canonicalTruth: '文穗事前写下了自主决定和信息边界的便条；玩家在第三日开场读到，便条不证明她此刻仍活着。',
      characters: ['fumi', 'player'], locations: ['home'],
      revelations: {
        clue: '文穗事前写下的便条说：“我想先自己把事情弄清楚。今天的安排由我来决定；你愿意听我说，再问我为什么。不要替我答应见谁，也别替我把不愿说的话交出去。”这证明她此前表明过边界，不能证明她此刻仍活着或已实际走完行程。',
      },
      availability: { minCycle: 3, locations: ['home'] },
    },
    {
      id: 'shared-supermarket-receipt', route: 'shared', kind: 'evidence',
      canonicalTruth: '便利店保留了文穗事前领取雨具与食品的签收底单，日期为9月8日；背面路线箭头接在水塔之后、山路之前，不证明9月9日实际来店。',
      characters: ['fumi'], locations: ['supermarket'],
      revelations: {
        hint: '便利店签收底单的背面画着几段路线。',
        clue: '9月8日签收底单与文穗留存联号码一致，确认她事前领取雨具和食品；背面写着“水塔后补给，再走山路”。这核实准备与计划顺序，不证明9月9日来过便利店。',
      },
      availability: { minCycle: 2, locations: ['supermarket'] },
    },
    {
      id: 'shared-senpai-camera', route: 'shared', kind: 'evidence',
      canonicalTruth: '学姐楼门口原始监控日期核对为9月8日，拍到文穗把小包交给灯织；寄存卡把取包列在山路之后、观景台之前，不能证明次日取包。',
      characters: ['fumi', 'touko'], locations: ['senpai-building'],
      revelations: {
        hint: '楼门口影像与寄存卡的日期需要分开核对。',
        clue: '楼门口原始监控核对为9月8日，拍到文穗把小包交给灯织；寄存卡写着“山路后取包，再去观景台”。影像证明事前寄存，卡片证明计划顺序，不能证明次日到场取包。',
      },
      availability: { minCycle: 2, locations: ['senpai-building'] },
    },
    {
      id: 'shared-observation-deck-plan', route: 'shared', kind: 'evidence',
      canonicalTruth: '事前路线页标注观景台为离开前最后一站；救援地点登记为观景台边坡，两份材料的位置相同不等于已验明文穗本人到过现场。',
      characters: ['fumi'], locations: ['observation-deck'],
      revelations: {
        hint: '事前路线页的终点，与救援位置登记落在同一区域。',
        clue: '文穗事前路线页写着“取包后去观景台，最后看一眼城市”；救援位置登记为观景台边坡。两份材料可核对地点，但初报身份未验明，不能据此确认她本人实际抵达。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 2, locations: ['observation-deck'] },
    },
    {
      id: 'shared-itinerary-crosscheck', route: 'shared', kind: 'evidence',
      canonicalTruth: '六处材料的日期、来源和路线标记完成交叉核对，重构出学校、水塔、便利店、山路、学姐楼、观景台的计划顺序；已核实的事前活动与未核实的本日目击分别列出，不能证明实际走完或此刻生还。',
      characters: ['fumi', 'player'], locations: ['home', 'water-tower', 'observation-deck'],
      revelations: {
        clue: '六处材料逐项对照，计划顺序为学校→水塔→便利店→山路→学姐楼→观景台。签收和寄存已核实为事前活动；校门、山路的本日身份与日期仍有空白，观景台仅有初报地点。核对完成表示材料边界已厘清，不能证明她实际走完或仍活着。',
      },
      availability: { minCycle: 4, locations: ['home', 'water-tower', 'observation-deck'], requiredClueIds: [...ITINERARY_FACT_IDS] },
    },
    {
      id: 'a-orphanage-contact', route: 'A', kind: 'evidence',
      canonicalTruth: '文穗事前询问周德明孤儿院身世资料，留存便笺与他的档案借阅回条对应；这只是联系动机，不证明见面或谋杀。',
      characters: ['fumi', 'old-man'], locations: ['water-tower', 'old-man-building'],
      revelations: {
        hint: '文穗的身世笔记留着一张档案借阅回条。',
        clue: '文穗写给周德明的孤儿院查询便笺，与他签名的档案借阅回条吻合；这说明她为何愿意联系他，不能证明实际会面或受害。',
      },
      availability: { minCycle: 2, locations: ['water-tower', 'old-man-building'], maxRevealBeforeRouteLock: 'clue' },
      suspicionTargets: ['old-man'],
    },
    {
      id: 'a-window-transfer-match', route: 'A', kind: 'evidence',
      canonicalTruth: '独立鉴定确认文穗坠落前遭控制性暴力；内室和二楼窗槽纤维、周德明的接触痕迹与她衣物吻合，检修通道原始录像及推车痕将楼后坠落点连到观景台边坡。',
      characters: ['fumi', 'old-man'], locations: ['old-man-building', 'observation-deck'],
      revelations: {
        clue: '核验过的伤情显示文穗坠落前已遭控制性暴力；内室与二楼窗槽纤维对应她的衣物，控制部位有周德明接触痕迹。楼后原始录像和推车痕记录他把坠落后的身体沿检修通道移到观景台边坡，排除了独自失足后一直留在原地的解释。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 4, locations: ['old-man-building', 'observation-deck'], requiresRouteLock: true, requiredClueIds: [...ROUTE_SUPPORT_FACTS.A] },
      suspicionTargets: ['old-man'],
    },
    {
      id: 'b-commission-message', route: 'B', kind: 'evidence',
      canonicalTruth: '赵刚与林静保存的委托讯息要求找到文穗并带去面谈，姓名和委托联络账号相符；委托本身不证明二人实际接触或造成死亡。',
      characters: ['fumi', 'detective-a', 'detective-b'], locations: ['detective-inn', 'community-hospital'],
      revelations: {
        hint: '委托联络中写有文穗的名字和面谈要求。',
        clue: '两名侦探的委托讯息写着“找到文穗，带来面谈”，姓名与联络账号已核对；这解释寻找目的，尚不能证明他们实际带人或使用暴力。',
      },
      availability: { minCycle: 3, locations: ['detective-inn', 'community-hospital'], maxRevealBeforeRouteLock: 'clue' },
      suspicionTargets: ['detective-a', 'detective-b'],
    },
    {
      id: 'b-contact-injury-match', route: 'B', kind: 'evidence',
      canonicalTruth: '文穗衣物撕裂与赵刚手部抓扯痕迹相符，水塔血液鉴定为文穗；原始录音与伤情匹配抓扯、失衡撞击铁件的先后，车辆录像记录林静随后接应转移，坠落不能解释先存的致命撞击。',
      characters: ['fumi', 'detective-a', 'detective-b'], locations: ['water-tower', 'detective-inn', 'observation-deck'],
      revelations: {
        clue: '原始录音与接触痕迹确认赵刚强行抓扯文穗，衣物撕裂、手部痕迹和铁件撞击点对应；血液归属与伤情时间核验表明她在冲突中失衡撞击致死。随后车辆录像记录林静接应转移，两人的通讯才有了具体对象，致命撞击与移尸是两个先后环节。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 4, locations: ['water-tower', 'detective-inn', 'observation-deck'], requiresRouteLock: true, requiredClueIds: [...ROUTE_SUPPORT_FACTS.B] },
      suspicionTargets: ['detective-a', 'detective-b'],
    },
    {
      id: 'c-night-gap-record', route: 'C', kind: 'evidence',
      canonicalTruth: '家中设备日志与楼道记录存在9月8日深夜到9月9日清晨的时间缺口，原始编号能同警方封存资料核对；缺口并不证明暴力或死亡。',
      characters: ['player', 'fumi'], locations: ['home', 'community-hospital'],
      revelations: {
        hint: '前夜的个人记事与设备日志有一段对不上的时间。',
        clue: '9月8日深夜到9月9日清晨的设备日志，与玩家记事存在具体时间缺口；楼道记录与警方封存编号可供后续对照。缺口只证明记忆和记录不合，不能代替暴力证据。',
      },
      availability: { minCycle: 3, locations: ['home', 'community-hospital'], maxRevealBeforeRouteLock: 'clue' },
      suspicionTargets: ['self'],
    },
    {
      id: 'c-domestic-injury-match', route: 'C', kind: 'evidence',
      canonicalTruth: '警方封存的原始家庭录音、门口影像、文穗颈部伤情与玩家手部接触痕迹相互对应，鉴定将窒息死亡时间定位到9月8日前夜家中争执时段，排除本日外出后坠亡；证明来自外部物证而非病历或症状。',
      characters: ['player', 'fumi'], locations: ['home', 'community-hospital'],
      revelations: {
        clue: '警方封存录音记录玩家在家中争执时威胁并压制文穗，门口影像排除该时段外人进入；颈部伤情、手部接触痕迹与录音时段吻合，独立鉴定把窒息死亡定位到9月8日前夜。证据指向玩家施暴，病历、解离与记忆缺口都不是定罪依据。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 4, locations: ['home', 'community-hospital'], requiresRouteLock: true, requiredClueIds: [...ROUTE_SUPPORT_FACTS.C] },
      suspicionTargets: ['self'],
    },
    {
      id: 'none-railing-maintenance', route: 'NONE', kind: 'evidence',
      canonicalTruth: '观景台维修工单事前登记过栏杆锚栓锈蚀与排水不畅；工单只证明潜在危险，不能证明文穗在此失足。',
      characters: ['fumi'], locations: ['observation-deck'],
      revelations: {
        hint: '栏杆锚栓旁的旧维修编号能在工单中找到。',
        clue: '暴雨前的维修工单登记了栏杆锚栓锈蚀和步道积水，现场编号吻合；它确认存在危险条件，不能单独证明有人失足，更不能证明没有凶手。',
      },
      availability: { minCycle: 3, locations: ['observation-deck'], maxRevealBeforeRouteLock: 'clue' },
    },
    {
      id: 'none-unassisted-fall-record', route: 'NONE', kind: 'evidence',
      canonicalTruth: '观景台原始连续录像核验了日期与文穗身份，记录她独行到湿滑步道、踩空抓扶栏杆而锚栓断裂坠落；现场足迹与伤情一致，没有先存的他人接触伤，支持事故而非仅凭无人可疑排除谋杀。',
      characters: ['fumi'], locations: ['observation-deck'],
      revelations: {
        clue: '核验日期与身份的原始连续录像记录文穗独行到观景台，在积水处踩空、抓扶时栏杆锚栓断裂；接近到坠落全程没有第二人接触。足迹、锈蚀断口和伤情与画面吻合，且无先存控制伤，才把离开计划与意外死亡机制分别证实。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 4, locations: ['observation-deck'], requiresRouteLock: true, requiredClueIds: [...ROUTE_SUPPORT_FACTS.NONE, ...ITINERARY_FACT_IDS] },
    },
    {
      id: 'fake-misidentification-chain', route: 'FAKE', kind: 'evidence',
      canonicalTruth: '救援初报把附近遗失物标签上的文穗姓名抄入无名遗体暂记表，后续电话沿用了姓名；没有直接验身签字。这证明初报程序没有可靠确认身份，不提前证明文穗生还。',
      characters: ['fumi'], locations: ['community-hospital', 'observation-deck'],
      revelations: {
        hint: '姓名先出现在遗失物标签，后被抄进暂记表。',
        clue: '交接原件显示，初报把附近遗失物标签上的文穗姓名抄入无名遗体暂记表，后续电话直接沿用；没有亲属验身或正式身份鉴定签字。误认可能由此形成，仍须分别核验遗体和离开后的本人活动。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 3, locations: ['community-hospital', 'observation-deck'], requiredClueIds: ['fake-body-mismatch'], maxRevealBeforeRouteLock: 'clue' },
    },
    {
      id: 'fake-verified-survival', route: 'FAKE', kind: 'evidence',
      canonicalTruth: '受托人员在离开后的落脚处面对面核对文穗的原始身份证明、旧伤与仅本人掌握的约定，带时间签章的回执确认生还。正式遗体核验排除文穗，灯织事前只保管小包与联络，文穗获知误认后暂不纠正；公开追问会让循玩家踪迹的委托方找到她。',
      characters: ['fumi', 'touko', 'player'], locations: ['senpai-building', 'observation-deck', 'community-hospital'],
      revelations: {
        clue: '离开后带时间签章的面对面核验回执，将本人证件、旧伤与私下约定三项核对为文穗；正式遗体鉴定同时排除她。她的留存说明与灯织交接记录一致：灯织事前只代存小包、转交联络，文穗获知初报误认后选择暂不纠正，没人取得或摆布遗体。回执明确要求不公开落脚处：委托方正循玩家的打听追查，继续散播车次和去向会暴露她。',
      },
      availability: { notBeforeTime: '16:00', minCycle: 4, locations: ['senpai-building', 'observation-deck', 'community-hospital'], requiresRouteLock: true, requiredClueIds: [...ROUTE_SUPPORT_FACTS.FAKE], requiredAnyClueIds: [...FAKE_PREPARATION_FACTS] },
    },
  ],
  npcKnowledge: [
    { npcId: 'school-guard', factId: 'shared-school-absence', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'school-guard', factId: 'shared-male-leave-call', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'school-guard', factId: 'shared-nurse-school-inquiry', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'morning-witness', factId: 'shared-detective-tail', maxRevealLevel: 'hint', stance: 'knows' },
    { npcId: 'touko', factId: 'shared-water-tower-secret', maxRevealLevel: 'hint', stance: 'suspects' },
    { npcId: 'old-man', factId: 'a-sacrifice-list', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'old-man', factId: 'a-lured-inside', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'old-man', factId: 'a-murder-staged-fall', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'shared-detective-tail', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'b-water-tower-blood', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'b-detective-coverup', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-a', factId: 'b-accidental-killing', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-b', factId: 'b-detective-coverup', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'detective-b', factId: 'b-accidental-killing', maxRevealLevel: 'confirmation', stance: 'lies-about' },
    { npcId: 'touko', factId: 'fake-touko-request', maxRevealLevel: 'clue', stance: 'knows' },
    { npcId: 'old-man', factId: 'cult-old-man-remembers-loop', maxRevealLevel: 'clue', stance: 'lies-about' },
  ],
};
